### ISSUE TITLE
app.config not loaded in gauge project

### ISSUE THREAD

**Issue by bkim54** [getgauge/gauge-csharp#101]
`ConfigurationManager.AppSettings.Count ` returns 0 when I do have appSettings within my app.config file inside my gauge project. 

### Gauge version
Gauge version: 0.7.0

Plugins
-------
csharp (0.9.2)

**Comment by sriv** [comment]
I believe that by default the `app.config` files are mapped to executables. In case of a gauge project the output is a class library. You could try using an approach like [this](http://stackoverflow.com/a/5191101/326543) and see if it helps.

Do post back if this does not work. There is a [related issue](https://github.com/getgauge/gauge-csharp/issues/50), for which we made some changes in the way gauge-csharp looks up configuration.

**Comment by bkim54** [comment]
@sriv I am creating a library that is to be consumed as a nuget package so I am using config file transforms to get my appSettings into the consuming project. 

I found this within the source https://github.com/getgauge/gauge-csharp/blob/b2910a7384b2ca15754060304a14f0244e7a24d8/Runner/Sandbox.cs#L309

it seems the gauge runtime can find the proper config file but it can't load it within a mono runtime? can this be worked around or not?

**Comment by sriv** [comment]
@bkim54 , I did not realize you were using this on mono! Yes, Mono does not support this feature I'm afraid!

**Comment by bkim54** [comment]
@sriv ah thanks.
