### ISSUE TITLE
Difference in behavior when plugin is not installed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#103]
In java if the plugin is not installed and I initialize the project, it initializes the project. Tells me that the compatible plugin is not installed. Downloads and installs it.

However c# and ruby do not share the same behavior

**Version**
```
Gauge version: 0.8.0.nightly-2017-02-06

Plugins
-------
```

**Comment by sriv** [comment]
## Dev Notes

Plugin installation is done by `gauge`, could be a potential gauge core issue. Needs verification.

**Comment by BugDiver** [comment]
This issue was moved to getgauge/gauge#564
