### ISSUE TITLE
Tags with execution hooks is not working

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#106]
[Hooks with Tags (2).zip](https://github.com/getgauge/gauge-csharp/files/763920/Hooks.with.Tags.2.zip)
The before spec is defined with tags. 

Running the specs is not printing on the console

**Comment by BugDiver** [comment]
Not able to produce with the current nightly of gauge and gauge-csharp.

**Comment by BugDiver** [comment]
By default tags provided to hooks uses `&` operator.
i.e. A BeforeSpec hook `[BeforeSpec("tag1","tag2")]` will be executed only for specs which are tagged with both the tags( `tag1` and `tag2`).
