### ISSUE TITLE
No Screenshots are attached to failed case when I Run gauge script in teamcity remotely .

### ISSUE THREAD

**Issue by AbinashB** [getgauge/gauge-csharp#109]

**Comment by AbinashB** [comment]
<img width="1055" alt="screen shot 2017-05-02 at 12 43 06 pm" src="https://cloud.githubusercontent.com/assets/21189978/25607688/5dfb3b14-2f35-11e7-8673-3d74535fb7c1.png">

**Comment by Apoorva-GA** [comment]
@AbinashB Are you using custom or in built screenshot?
And also can we know what version of html-report are you using? Please run `gauge -v` and send us the output.

**Comment by AbinashB** [comment]
i am using:-
csharp (0.9.2)
html-report (2.1.1)
if I run the script in my local system screenshots are coming. but running in teamcity agent in the remote machine is not working.
No, I have not used any custom or in built screenshot.

**Comment by Apoorva-GA** [comment]
@AbinashB Could you please update your html-report to the latest (3.1.0) and check if you still face the issue.

**Comment by AbinashB** [comment]
getting :- PS C:\Users\te> gauge --update html-report
Gathering metadata for html-report
Plugin html-report 2.1.1 is already installed.   
what is the command to manually  install for particular version?

**Comment by Apoorva-GA** [comment]
You can use this command `gauge --update html-report --plugin-version 0.3.1` for more info refer https://docs.getgauge.io/plugins.html?highlight=update

**Comment by AbinashB** [comment]
thank you for the command.Let me try.

**Comment by Apoorva-GA** [comment]
@AbinashB latest html-report version is 3.1.0  so use this command `gauge --update html-report --plugin-version 3.1.0` also please install latest gauge (0.8.3).

**Comment by AbinashB** [comment]
same issue after update also: 
PS C:\Users\te> gauge -v
Gauge version: 0.8.3

Plugins
-------
csharp (0.10.0)
html-report (3.1.0)

Locally able to get screenshots but when running through teamcity agent not able to get failed screenshot.

**Comment by Apoorva-GA** [comment]
Could you check if `screenshot_on_failure` flag is set to true in your CI. Take a look over [here](https://docs.getgauge.io/configuration.html?local-project-level#local-project-level) for more details.

**Comment by AbinashB** [comment]
Yes, This flag is set to true. actually, if I go to that build machine and run locally, able to see the screenshots. if running through teamcity then only not able see screenshots attached to report in the artifact.

**Comment by sriv** [comment]
@AbinashB  - in CI environment, the default screenshot mechanism is not very reliable, since it simulates a <kbd>Print Screen</kbd> action.

I suggest that you consider using custom screenshots as illustrated [here](https://docs.getgauge.io/language.html#id21).

Closing this issue, feel free to comment if this requires further attention.
