### ISSUE TITLE
is there any tag to support dependency ?

### ISSUE THREAD

**Issue by AbinashB** [getgauge/gauge-csharp#110]
One TestCase/TestScenario is depended on another TestCase/TestScenario.
How to implement on gauge.
 
Example: in TestNG: @Test(dependsOnGroups = { "add" })

**Comment by Apoorva-GA** [comment]
@AbinashB this feature is currently not supported in gauge.

**Comment by sriv** [comment]
Closing this issue, feel free to comment if this requires further attention.
