### ISSUE TITLE
GaugeMessages.WriteMessage is not writing any message

### ISSUE THREAD

**Issue by fruityoat** [getgauge/gauge-csharp#117]
### Expected behaviour
`GaugeMessages.WriteMessage` should write a message to the html report.

### Actual behaviour
`GaugeMessages.WriteMessage` doesn't write anything to the html report.

### Steps to reproduce
1. Create spec
```
write message
==================
Gauge write message
-----------
* Should be printed in html
```
2. Implement step
```
[Step("Should be printed in html")]
public void WriteMsg()
{
    GaugeMessages.WriteMessage("bla");
}
```
3. Run the spec. The html report should contain 'bla'.

### Gauge version
```
Gauge version: 0.9.6
Commit Hash: 571fda8

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
screenshot (0.0.1)
xml-report (0.2.0)
```
Possibly related: [html #111](https://github.com/getgauge/html-report/issues/111). Apparently fixed but still doesn't work in c#

**Comment by jorgecunhamorsum** [comment]
I'm seeing the same behavior but with Java.

**Comment by sguptatw** [comment]
**Working as expected in version**
```
Gauge version: 1.0.1.nightly-2018-08-01
Commit Hash: 6aa1ce2

Plugins
-------
csharp (0.10.5.nightly-2018-08-02)
```
