### ISSUE TITLE
Plugin version will not update to 0.10.3

### ISSUE THREAD

**Issue by smathistad** [getgauge/gauge-csharp#127]
The plugin version will not update to 0.10.3 using the gauge update command.

Running the command "gauge update -a" just returns the message "Successfully updated all the plugins." without doing anything.  The plugins are still at the same versions as before.

Running the command "gauge update csharp" returns no message and the csharp plugin is still at the same versions as before.

### Gauge version
```
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
csharp (0.10.2)
html-report (4.0.3)
java (0.6.6)
json-report (0.2.1)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by sriv** [comment]
Thanks for reporting. I think the metadata is messed up. Looking into this.

**Comment by sriv** [comment]
Can you please attempt once more ? Csharp 0.10.3 was marked with a requirement of minimum gauge 0.9.8, but I think it should work with gauge 0.9.7. Have posted the changes.

If it doesn't work, try uninstalling + reinstalling the csharp plugin.

**Comment by smathistad** [comment]
Works great now.  Thanks.
