### ISSUE TITLE
Make CSharp Runner build Configuration and Platform Configurable

### ISSUE THREAD

**Issue by mflick89** [getgauge/gauge-csharp#131]
Problem:
Current CSharp Runner will always build C# gauge tests as "Any CPU" and "Debug" by default.
This can cause difficulties when wanting to test some x64 environments or custom configurations.

Proposed Solution:
Add variables to csharp.properties that allow users to define the Configuration and Platform of the build run by the CSharp Runner.

Example:
The build configuration when running tests for the Gauge project
GAUGE_CSHARP_PROJECT_CONFIG = Debug

The build platform when running tests for the Gauge project
GAUGE_CSHARP_PROJECT_PLATFORM = Any CPU

**Comment by mflick89** [comment]
I'd like to assign this issue to myself.

**Comment by sriv** [comment]
Thanks for raising this. Looking at the PR now.

**Comment by sriv** [comment]
should be available in nightly >= 14/06/2018

**Comment by sguptatw** [comment]
**Question**
```
GAUGE_CSHARP_PROJECT_CONFIG = Debug

GAUGE_CSHARP_PROJECT_PLATFORM = Any CPU
```
Should these configurations be available in csharp.properties when a new project is created?

**Comment by mflick89** [comment]
It would be nice to have them there.
It is not required since the code will default these values if they are missing, but it would be nice to have them there by default to make it obvious to the user that the options are available.
