### ISSUE TITLE
GaugeScreenshots.Capture() is not capturing screenshot

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge-csharp#155]
### Expected behavior
I should be able to capture screenshot using GaugeScreenshots.Capture() 

### Actual behavior
Gauge is not capturing screenshot when using GaugeScreenshots.Capture();

### Steps to reproduce
1. Create a .Net Core project using Gauge
2. Create a step implementation
3. Use GaugeScreenshots.Capture(); in step implementation\
I have html plugin installed and i am not getting any error message during execution but it just doesn't capture any screenshot. As per my understanding i should see screenshot in Gauge html report. Please advise.

### Gauge version
Gauge version: 1.0.2
Commit Hash: b4288bb

Plugins
-------
csharp (0.10.5)
dotnet (0.1.0)
html-report (4.0.6)
screenshot (0.0.1)

**Comment by mrbcmorris** [comment]
I've run into this myself.  however I'm using Gauge 1.0.3  Commit Hash ff6c0c3

**Comment by manavghaigithub** [comment]
@NivedhaSenthil  I am not seeing any screenshot in the report with .Net Core. Can you share sample report to show how it looks like?

**Comment by NivedhaSenthil** [comment]
It gets added to steps in report like below from where ever it is captured.
<img width="1679" alt="screen shot 2019-02-06 at 9 41 50 am" src="https://user-images.githubusercontent.com/6358540/52320147-a72c4980-29f3-11e9-8965-6b3c0a03678e.png">

**Comment by manavghaigithub** [comment]
Are you trying it in .Net Core? I dont see screenshots in report in .Net Core project

________________________________

**Comment by NivedhaSenthil** [comment]
Yes, I am trying with .Net core

**Comment by NivedhaSenthil** [comment]
Dint realise I was in a different version of html-report plugin, could replicate the issue with `4.0.6` https://github.com/getgauge/html-report/issues/211. Please try using the nightly build or older version html-report while we release the fix.

**Comment by manavghaigithub** [comment]
Nightly builds are not yet available due to restricts in the company. When do you think this can be fixed?
________________________________

**Comment by mrbcmorris** [comment]
I'm using gauge-csharp and encountering the same issue.  I've tried ```4.0.5``` and ```4.0.7.nightly-2019-02-05``` of html-report to no avail.

**Comment by Apoorva-GA** [comment]
Html-report [4.0.7](https://github.com/getgauge/html-report/releases/tag/v4.0.7) is released. 
Update the plugin to get the latest changes and do let us know if the issue is fixed.

**Comment by mrbcmorris** [comment]
hi @Apoorva-GA , I'm still encountering the issue after installing ```4.0.7```

```
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
csharp (0.10.5)
dotnet (0.1.0)
html-report (4.0.7)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by manavghaigithub** [comment]
Yeah it’s not working for me as well after upgrading html report plugin to 4.0.7


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NivedhaSenthil** [comment]
@manavghaigithub  and @mrbcmorris can you please try uninstalling the html-report plugin and try with a fresh sample project ?

**Comment by mrbcmorris** [comment]
Hi @NivedhaSenthil,

I have tried the recommended steps and resulted in the same issue.  After uninstalling gauge wasn't able to locate html-report so I downloaded ```4.0.7``` from the [gauge/html-report](https://github.com/getgauge/html-report/releases) repo.

My StepImplentation after scaffolding:
```
using System;
using System.Collections.Generic;
using System.Linq;
using FluentAssertions;
using Gauge.CSharp.Lib;
using Gauge.CSharp.Lib.Attribute;

namespace screenshot
{
    public class StepImplementation
    {
        private HashSet<char> _vowels;

        [Step("Vowels in English language are <vowelString>.")]
        public void SetLanguageVowels(string vowelString)
        {
            GaugeScreenshots.Capture();
            _vowels = new HashSet<char>();
            foreach (var c in vowelString)
            {
                _vowels.Add(c);
            }
        }

        [Step("The word <word> has <expectedCount> vowels.")]
        public void VerifyVowelsCountInWord(string word, int expectedCount)
        {
            var actualCount = CountVowels(word);
            actualCount.Should().Be(expectedCount);
        }

        [Step("Almost all words have vowels <wordsTable>")]
        public void VerifyVowelsCountInMultipleWords(Table wordsTable)
        {
            var rows = wordsTable.GetTableRows();
            foreach (var row in rows)
            {
                var word = row.GetCell("Word");
                var expectedCount = Convert.ToInt32(row.GetCell("Vowel Count"));
                var actualCount = CountVowels(word);

                actualCount.Should().Be(expectedCount);
            }
        }

        private int CountVowels(string word)
        {
            return word.Count(c => _vowels.Contains(c));
        }
    }
}
```

**Comment by manavghaigithub** [comment]
Hi @NivedhaSenthil - It is the same behavior happening with me as well. I uninstalled and reinstalled htl-report plugin but due to some reason it is not capturing screenshots in report.

**Comment by manavghaigithub** [comment]
@NivedhaSenthil Sorry for bugging you on this, just wanted to check whether you got a chance to look into this? Please advise.

**Comment by BugDiver** [comment]
@manavghaigithub, @mrbcmorris   I could replicate the issue witth `gauge-dotnet: 0.1.0`.
This has been fixed but the plugin is not released yet.
We will be making a release soon. Meanwhile, you can try installing `gauge-dotnet` nightly version and see if it fixes the issue. Refer [this](https://github.com/getgauge/gauge-dotnet#nightly-installation) to see install instructions.

**Comment by Debashis9012** [comment]
We are able to reproduce this in ```gauge-dotnet: 0.1.0```
But its woking properly with the below version

```
Gauge version: 1.0.5.nightly-2019-02-08
Commit Hash: 6971850

Plugins
-------
dotnet (0.1.1.nightly-2019-01-29)
```

**Comment by mrbcmorris** [comment]
hi @Debashis9012,

I can confirm this nightly builds for dotnet and csharp have remedied the issue.

```
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
csharp (0.10.6.nightly-2019-01-11)
dotnet (0.1.1.nightly-2019-01-29)
html-report (4.0.7)
screenshot (0.0.1)
xml-report (0.2.0)
```
