### ISSUE TITLE
Nuget package DLL's in gauge_bin folder

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge-csharp#157]
### Expected behavior
Gauge should remove DLL's from gauge_bin folder once the package that was added through NuGet is removed from Gauge .Net Core project

### Actual behavior
Gauge is not removing DLL's from gauge_bin folder once the package that was added through NuGet is removed from Gauge .Net Core project

### Steps to reproduce
1. Create a new .Net Core project through Gauge
2. Create any sample/test Step Implementation
3. Add Nuget Package through Manage Nuget in Visual Studio. For e.g. add Selenium.WebDriver.
4. When you remove this package from Manage Package, the associated Selenium DLL's does not get removed from gauge_bin folder. They should get removed because i dont need them anymore.

### Gauge version
Gauge version: 1.0.2
Commit Hash: b4288bb

Plugins
-------
csharp (0.10.5)
dotnet (0.1.0)
html-report (4.0.6)
screenshot (0.0.1)

**Comment by BugDiver** [comment]
@manavghaigithub The `gauge_bin` folder is used to build the project, which copies the required DLL's from nuget cache to `gauge_bin`.
It happened at runtime. So when you remove the package from `Manage Package` gauge would know about it.
But It should be removed when you run the `tests` next time or restart the VS.

We currently do not support `.Net core` for visual studio. Please refer https://github.com/getgauge/gauge/issues/1288#issuecomment-453373955

**Comment by manavghaigithub** [comment]
Hey Vijay - I will try to remove package from terminal in viscose and then will restart viscose to see whether it is happening or not.


Thanks,
Manav Ghai
________________________________

**Comment by BugDiver** [comment]
@manavghaigithub Closing it for now since `.Net core` is not supported on  `Visual Studio`.
