### ISSUE TITLE
Change MSBuild version for project building

### ISSUE THREAD

**Issue by s0ren1** [getgauge/gauge-csharp#163]
### Expected behavior
Whenever I execute gauge validate in the server where my gauge script I expect something like this (like in my local machine):
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe

### Actual behavior
but it points to
D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe

### Gauge version
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
csharp (0.10.5)
html-report (4.0.5)
screenshot (0.0.1)

(in both my local and the server)

The server is an azure webApp and current scripts have been working well as they run fine using the MSBuild 14.0. However, the new script uses a syntax that requires the MSBuild 15.0.

Now, in the azure web app I do see a MSBuild 15.0 folder but is located in 

D:\Program Files (x86)\MSBuild-15.3.409.57025\MSBuild> 

I would like to have gauge to point to this folder instead. Is there a way to do that?

**Comment by negiDharmendra** [comment]
@s0ren1 You can  do this by setting `MSBuild` env variabl to the location of `MSBuild.exe` executable or the directory conatining `MSBuild.exe` file.
**Example:**
 -  $env:MSBuild="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
 - OR  $env:MSBuild="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe"

**Comment by nehashri** [comment]
@s0ren1 Please try the suggestion given by @negiDharmendra. If you are still facing issue, please reopen this issue.
