### ISSUE TITLE
Add message to migrate to dotnet plugin

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-csharp#164]
Microsoft announced the end of .Net Framework (see https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/). This plugin supports only .Net Framework. We need to advice our users to use our [dotnet plugin](https://github.com/getgauge/gauge-dotnet) in order to work with .Net Core. The following needs to be done :
1. Add a message in the readme about our dotnet plugin. And a deprecation warning, as soon as Microsoft stops supporting .Net Framework, Gauge will also stop supporting it.
2. Every time Gauge Csharp is installed, a note telling users that this plugin works with only .Net Framework, in order to use .Net Core please download dotnet plugin.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed against 0.10.6.nightly-2019-07-15
