### ISSUE TITLE
Structure log messages

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-csharp#165]
Gauge can now understand plugin's log messages when it is structured properly (refer getgauge/gauge#216) for changes made in Gauge. The runner must now start logging in this format so that Gauge understands the messages properly.

**Comment by Debashis9012** [comment]
Verified against ```gauge-csharp-0.10.6.nightly-2019-07-10``` version.

**Comment by Debashis9012** [comment]
csharp plugin's log messages appearing in structured mannered.
Its has been verified and found fixed.
```
Gauge version: 1.0.6.nightly-2019-07-16
Commit Hash: 75d9328

Plugins
-------
csharp (0.10.6.nightly-2019-07-15)
```
