### ISSUE TITLE
The gauge package did not load correctly

### ISSUE THREAD

**Issue by PODHUPU** [getgauge/gauge-csharp#170]
![Capture](https://user-images.githubusercontent.com/31724051/62986712-31aca480-be80-11e9-8e77-58f4695f97e9.PNG)

### Expected behavior
Tell us what should happen
It should launch gauge plugin template

### Actual behavior
Tell us what happens instead
It is not opening the gauge template and gives error 

### Steps to reproduce
1.Download gauge visual studio plugin
2.Restart
3.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

**Comment by BugDiver** [comment]
@PODHUPU Could please give us more information about your environment like 
* Gauge and gauge-csharp plugin version
* Gauge Visual Studio plugin version
* Visual Studio version

**Comment by PODHUPU** [comment]
Gauge version: 1.0.5 
Commit Hash: 562f036 

Plugins
-------
csharp (0.10.5)      
html-report (4.0.8)  
screenshot (0.0.1)   
xml-report (0.2.1)

**Comment by luciferankon** [comment]
@PODHUPU You need to install Gauge Visual Studio template also you can get that [here](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1071478.gauge-visualstudio-templates). Please come back if the issue persist

**Comment by nehashri** [comment]
@PODHUPU Please reopen this issue if you still facing problems.
