### ISSUE TITLE
Pass execution info to the runner

### ISSUE THREAD

**Issue by ApoorvaM** [getgauge/gauge-csharp#18]
Currently the ExecutionHooks do not receive the ExecutionInfo in any form. Have a way to pass relevant context information to Hook and Step execution.

Note: Passing the `ExecutionInfo` object as is, would mean having the entire proto generated classes in the Lib, which is probably a bad idea.

**Comment by sriv** [comment]
The immediate need for ExecutionInfo is to filter hooks execution by tags, addressed by #17. Closing this for now.
