### ISSUE TITLE
Provide an api to add custom messages into reports

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/gauge-csharp#24]
As a part of [this issue](https://github.com/getgauge/gauge/issues/121), need an API for the user to enter custom messages at runtime. These messages will be added to the reports on execution. 
The runner needs to collect these messages and add them into the ExecutionResult that is passed with the StepExecutionResult after every step executes.

Proposed API (similar to the one in [Java runner](http://getgauge.io/documentation/user/current/test_code/java/custom_messages_in_reports.html))
````c#
Gauge.writeMessage("Simple message")
````

**Comment by apoorvam** [comment]
Fixed in this [commit](https://github.com/getgauge/gauge-csharp/commit/6163e4cb11b7db80599fb7f6db09ff4008e4b5aa).

It should be used as :
```
GaugeMessages.WriteMessage("hello world");
or
GaugeMessages.WriteMessage("hello {0}", "world");
```
