### ISSUE TITLE
Unable to debug step from IDE

### ISSUE THREAD

**Issue by abhijeet4046** [getgauge/gauge-csharp#35]
i install the gauge on my win 7 machine and sample example also , now i want to debug the stepdefination , i have to place break point on my first step def but its unable to debug

see this pic
![image](https://cloud.githubusercontent.com/assets/11377669/9732875/d82084f6-5644-11e5-87e4-99409676e94e.png)

**Comment by abhijeet4046** [comment]
please any one  suggest me flow of installing gauge csharp and run & debug  scenario 
Both way command promt also and IDE(visual studio 2013)

Thanks in Advance

**Comment by mahendrakariya** [comment]
Can you please share what version of gauge you are using? You can get the details by running `gauge -v` on command prompt.

You can install gauge csharp using gauge [installer](http://getgauge.io/download.html) by selecting the `C#` option under language plugins. Or you can run `gauge --install csharp` on command prompt. After this, you should ideally be able to run and debug your tests from VS (assuming you have [VS Gauge package](https://visualstudiogallery.msdn.microsoft.com/dd8ea767-aa75-4771-98f4-6c8a9055ca92) installed).

If you still face any issues, please feel free to get back to us.

**Comment by abhijeet4046** [comment]
hii mahendra thanks for the reply...
  i  am using gauge version 0.1.7
and i install gauge csharp using installer with selecting c# under languages 
and in my VS install "gauge  VS 2013" package in my VS 2013 
I create 'gauge test project'  by create new project and 
trying to run or debug    first scenario its not showing any error or result scenario always false 

When i trying from command prompt i got errors  see in Pic
![cmd screen shot for gauge](https://cloud.githubusercontent.com/assets/11377669/9754596/83edb030-56e8-11e5-92c9-d7b6b80762fb.jpg)

**Comment by mahendrakariya** [comment]
From the screenshot, it looks like there is some issue with the internet connection. Gauge is not able to download the C# plugin. Just ensure you are not behind any proxy.

Alternatively, you can [download the plugin](https://github.com/getgauge/gauge-csharp/releases/download/v0.5.1/gauge-csharp-0.5.1.zip) zip file and do `gauge  -f <path_to_csharp_plugin_zip> --install csharp`

**Comment by abhijeet4046** [comment]
![image](https://cloud.githubusercontent.com/assets/11377669/9759235/3c9ea740-5709-11e5-8d4b-cf8b516f42dd.png)


installation done but on gauge --init csharp fails to create hello world.spec

**Comment by mahendrakariya** [comment]
This issue is likely to occur if something has gone wrong with Gauge installation. Could you please uninstall and reinstall Gauge?

After installation, just ensure that there is `skel` folder in C:\Program Files\Gauge\share\gauge.

**Comment by abhijeet4046** [comment]
![image](https://cloud.githubusercontent.com/assets/11377669/9762625/5f224b46-5722-11e5-918e-f77679725517.png)



in my Gauge folder there is only bin folder 
share folder is not present

**Comment by mahendrakariya** [comment]
That's wierd. It means something has gone wrong while installation. Could you please uninstall and reinstall Gauge?

**Comment by abhijeet4046** [comment]
Thanks so munch mahendra successfully done installation  

I add my DLLs  in GaugeTest project  which i want to Automate  after that  
 debuging  throwing following exception

Before the adding DDLs debugging successfully run its comming on break point


The exception is--
System.Reflection.ReflectionTypeLoadException was unhandled
Message: An unhandled exception of type 'System.Reflection.ReflectionTypeLoadException' occurred in Gauge.Csharp.Runner.exe
Additional information: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

**Comment by abhijeet4046** [comment]
When i run spec from command prompt  Then also throwing exception

![image](https://cloud.githubusercontent.com/assets/11377669/9764389/71c77bfe-572c-11e5-8f3d-9d3544d6458d.png)

**Comment by abhijeet4046** [comment]
You can check Exception in details here

![image](https://cloud.githubusercontent.com/assets/11377669/9782504/34009e74-57bb-11e5-97b8-72d65bcb8862.png)

I think its come on reading AssemblyFiles

**Comment by abhijeet4046** [comment]
Hii Mahendra...

Are you there We are waiting for your responce

**Comment by sriv** [comment]
We are trying to replicate a scenario where this happens, and will issue a fix. 

Please note - you can also join us at chat [here](https://gitter.im/getgauge/chat). I would suggest that you post any information relevant to the issue here, and ping us over chat as it is usually faster.

**Comment by sriv** [comment]
We've released 0.6.0 version of Gauge C# - it is still not available on the Gauge Repository, so you will have to do an offline install.

Can you please try these steps:
- Download Gauge CSharp v0.6.0 from [here](https://github.com/getgauge/gauge-csharp/releases/download/v0.6.0/gauge-csharp-0.6.0.zip)
- Run `gauge --install csharp -f gauge-csharp-0.6.0.zip` from the location where you saved the above file.
- Ensure that you have the [latest visual studio plugin](https://visualstudiogallery.msdn.microsoft.com/dd8ea767-aa75-4771-98f4-6c8a9055ca92) installed. Please note that there is a new VS Plugin available, which you will not see as an update.

Please let us know if this fixes the issue.

**Comment by abhijeet4046** [comment]
![image](https://cloud.githubusercontent.com/assets/11377669/9870318/80e1c876-5ba8-11e5-83fd-47e334f1b444.png)


my plugin version is 0.6.0

Gauge.Csharp.Lib version 0.5.2.0

still error is not resolved

**Comment by sriv** [comment]
This is strange. Could you upload a sample project with this error, that we can look at and troubleshoot?

**Comment by abhijeet4046** [comment]
our sample project is  running successfully
 when i add dll which i need for testing APIs
after that when i debug scenario or run then error occurs 

i have 20 -25 dlls for Api testing ,We can not share with you

**Comment by uzmar** [comment]
Can you delete bin, obj and gauge-bin directories then build solution and run gauge specs, it should work
Can you try it once? it worked for me(run from cmd prompt).

**Comment by abhijeet4046** [comment]
I delete bin and obj folder from my solution and i run spec from command prompt
then .....
![image](https://cloud.githubusercontent.com/assets/11377669/9875741/5302cfd8-5bce-11e5-82fb-49f1aa9bac4f.png)

**Comment by apoorvam** [comment]
It looks like there is an issue in executing a sample spec created by Gauge sample project. Can you please try 
```
mkdir test
cd test
gauge --init csharp
gauge specs
```
If this works fine, it should be some issue with project structure since the error message says it cannot locate a project file. 

Can you try this and confirm if its working?

**Comment by abhijeet4046** [comment]
the --Init csharp command is throwing exception 

i create project from visual studio 2013 (using gauge vs 2013) plugin 

in visual studio GoTo- file --> new --> project --> select Gauge test project 

its create folder structure of gauge  

![image](https://cloud.githubusercontent.com/assets/11377669/9876855/ca57d7ec-5bd6-11e5-9513-58d59dee0a8c.png)

**Comment by abhijeet4046** [comment]
Before Add dll its working fine

![image](https://cloud.githubusercontent.com/assets/11377669/9877128/8fc4b4ae-5bd8-11e5-8c23-887917f8ea3f.png)

After add references of my DLLs 
i run specs command 
![image](https://cloud.githubusercontent.com/assets/11377669/9877194/e692ad2c-5bd8-11e5-8b6a-1accbf1bfd00.png)

**Comment by sriv** [comment]
Looking at your console output, it looks like there is a conflict between different versions of the same assembly in your project. 

Right now if it not easy to tell which assembly is causing this conflict, just by looking at the console output/logs. I have created a new issue(#36) that would enable Gauge-CSharp to add this debug information.

Right now the only way to troubleshoot this is by debugging the project, by attaching the gauge-csharp runner to the debugger. Alternatively, please see if your `Event Viewer` or [`Fuslogvw`](https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx) to find out the assembly that is causing this problem.

**Comment by sriv** [comment]
#50 could be related. I am closing this, as one theory is that BindingRedirects are not being honoured, which is fixed via #50.
