### ISSUE TITLE
Do automatic type conversion

### ISSUE THREAD

**Issue by MattFenner** [getgauge/gauge-csharp#43]
I kind of expected this to work:
```
        [Step("Close and reopen the window <times> times")]
        public void CloseAndReopenWindow(int times)
        {
            
        }
```

however it fails with an error saying it cant convert the string type into an int type.

i think it would be a lot nicer if it automatically tried to convert (i.e. parse) to the argument type. 
Having to parse integers all the time would be a big pain, when it is something that would be pretty easy for the tool to do.

Also would be even better if there was a way to convert conversion for custom types e.g. you might have your own special Person type and implement a converter from a string for that type.

does anything like this exist in the product already, or is it planned?

**Comment by sriv** [comment]
Good idea. We do this for `Table` type, but we should try to extend this to the target method type.
