### ISSUE TITLE
file special parameter does not work in Visual Studio

### ISSUE THREAD

**Issue by roffster** [getgauge/gauge-csharp#47]
I'm using the <file:filename> special parameter in a .NET solution.  When I add a step that uses the file parameter, all the steps in the spec become unmatched with the step definitions and the spec is lost from the test explorer.

To get functionality back I have to remove the step using the parameter and restart Visual Studio

**Comment by sriv** [comment]
Looks like the gauge-csharp daemon is crashing, causing Visual Studio to not have any API response. Could you please check if there are any errors in the following places:

- `.\logs\gauge.log`
- `.\logs\api.log`
- Event Viewer Log

Please post back any information that will help troubleshoot this.

**Comment by roffster** [comment]
No problem....so I cleared out the gauge & api logs...added the following step

* use translations <file:Steps\Eu261\Translations\Es.txt>

the file exists in the Steps\Eu261\Translations directory relative to the root of the project.

There was no error in the gauge log, but in the api log I got

15:04:27.380 [INFO] Initializing concepts cache with 0 concepts
15:04:27.407 [INFO] Watching directory: D:\Projects\WebTestAutomation\easyJet.Automation.Gauge\specs
15:04:27.407 [INFO] Initializing specs cache with 3 specs
15:04:27.410 [INFO] Watching directory: D:\Projects\WebTestAutomation\easyJet.Automation.Gauge\specs\Eu261
15:04:27.495 [INFO] Initializing steps cache with 68 steps
15:04:32.032 [ERROR] Failed to respond to API request. Could not Marshal response proto: required field "AllSpecsResponse.Specs.Items.Scenario.Skipped" not set
15:04:33.373 [ERROR] Failed to respond to API request. Could not Marshal response proto: required field "AllSpecsResponse.Specs.Items.Scenario.Skipped" not set
15:05:15.751 [INFO] Spec file removed: D:\Projects\WebTestAutomation\easyJet.Automation.Gauge\specs\Eu261\EU261_Translations.spec
15:05:15.751 [INFO] Spec file added / modified: D:\Projects\WebTestAutomation\easyJet.Automation.Gauge\specs\Eu261\EU261_Translations.spec
15:05:15.762 [ERROR] Spec Parse failure: [ParseError] D:\Projects\WebTestAutomation\easyJet.Automation.Gauge\specs\Eu261\EU261_Translations.spec : line no: 302, Dynamic parameter <file:StepsEu261TranslationsEs.txt> could not be resolved

**Comment by roffster** [comment]
I think GitHub is stripping the <> chars around the special parameter, but the file parameter is enclosed in them

**Comment by roffster** [comment]
the file parameter is \<file:Steps\\Eu261\\Translations\\Es.txt\>

**Comment by sriv** [comment]
This is probably an issue with Gauge core. Could you please try something:

Use one of the below options to specify your file location, i.e. instead of `<file:Steps\Eu261\Translations\Es.txt>` choose

- `<file:Steps\\Eu261\\Translations\\Es.txt>`
- `<file:Steps/Eu261/Translations/Es.txt>`

My theory is that single back-slash is being escaped, but I request you to confirm at your end.

**Comment by roffster** [comment]
I think you've fixed it...certainly the VS plugin no longer crashes when using the file parameter...will do more testing today.  

I did notice though that I can crash the plugin if the path specified in the file parameter is incorrect
