### ISSUE TITLE
visual studio tests isssue

### ISSUE THREAD

**Issue by marek2209** [getgauge/gauge-csharp#49]
hi, 
I after rebuild a application i cant see any tests. I have installed VS 2015 premium. This is the output from VS.I have the latest version of gauge

Gauge version: 0.3.2

Plugins
-------
csharp (0.7.1)
html-report (2.0.0)
ruby (0.1.0)

1>------ Rebuild All started: Project: Gauge.Example, Configuration: Debug Any CPU ------
1>  Gauge.Example -> C:\Users\user\Documents\Visual Studio 2015\Projects\gauge-example-csharp-master\bin\Debug\Gauge.Example.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

![image](https://cloud.githubusercontent.com/assets/9087374/13171626/1a3b45ee-d6f4-11e5-8063-e8d0e5eed24a.png)

**Comment by sriv** [comment]
Hi, is this happening despite you installing the plugin as admin?

**Comment by marek2209** [comment]
Problem solved sorry . Just delte this topic

**Comment by sriv** [comment]
Oh good, so are you now able to see tests and run them fine?

**Comment by marek2209** [comment]
Now i onlyy see tests in test explorer but i still cant run them.. I described this issue in this topic https://github.com/getgauge/gauge/issues/299

**Comment by sriv** [comment]
OK, just checking. Will investigate more once I get to the computer.

**Comment by sriv** [comment]
Could you please try Gauge-VisualStudio [v0.2.1](https://visualstudiogallery.msdn.microsoft.com/dd8ea767-aa75-4771-98f4-6c8a9055ca92)? This should be fixed. I am closing this issue, please feel free to reopen if you still face problems.
