### ISSUE TITLE
Provide Execution Context to implementation

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-csharp#53]
Have a way to expose context around the execution. The [ExecutionInfo](https://github.com/getgauge/gauge-proto/blob/master/messages.proto#L77) type can be marshalled and converted to a custom type.

It should expose:
- Current Spec
- Current Scenario
- Current Step

**Comment by sriv** [comment]
Should also work for execution hooks.

**Comment by sguptatw** [comment]
Currently only the execution hooks have the context and not the step implementation.

**Comment by SreejithShenoi** [comment]
We are eagerly waiting for ExecutionContext to be availble for execution hooks in C#. Any plans on when this would be available?

**Comment by sguptatw** [comment]
The ExecutionContext is available for hooks

Here is an example
```
            using Gauge.CSharp.Lib;
            using static Gauge.CSharp.Lib.ExecutionContext;

            [BeforeScenario]
            public void BeforeScenario(ExecutionContext context)
            {
                String scenarioName = context.CurrentScenario.Name;
                //Code for before scenario
            }

            [AfterSpec]
            public void AfterSpec(ExecutionContext context)
            {
                Specification specification = context.CurrentSpecification;
                //Code for after spec
            }
```

Verified on version
```
Gauge version: 0.9.9.nightly-2018-06-01
Commit Hash: 812f26e

Plugins
-------
csharp (0.10.4.nightly-2018-05-29)
```
