### ISSUE TITLE
No error when multiple step implementations exist

### ISSUE THREAD

**Issue by hakito** [getgauge/gauge-csharp#55]
When I have two step implementations with the same stepText:

```
public class StepImplementation
{
	[Step("Duplicate step")]
	public void DuplicateStep1()
	{
		Console.Out.WriteLine("Duplicate Step 1");
	}

	[Step("Duplicate step")]
	public void DuplicateStep2()
	{
		Console.Out.WriteLine("Duplicate Step 2");
	}
}
```
... the runner gives no error about ambiguous step definiton. In my case it simply executed DuplicateStep2.

In our case we had 2 step implementations with the same stepText in different assemblies.

Expected behavior:
* Warning on scanning for step implementations
* Error when trying to execute an ambiguous step

**Comment by sriv** [comment]
Gauge should also have this behaviour consistent across languages.

**Comment by hakito** [comment]
Are you sure? I didn't study the whole architecture of gauge and runner communication. But as far as I understood: Gauge simply loads the runner, and calls the steps from the specs file, and has no information about the actual stepNames.

But maybe I am wrong.

**Comment by sriv** [comment]
Gauge does most of the orchestration, but the core isn't aware of implementation (which is language specific). What I meant here is - this problem exists in other language runners as well, we need to address it there as well.

The implementation for this would be at language runner level.(In this case, the change would be in gauge-csharp). 

Then there is also the aspect of IDE plugins being aware of these rules, but we should address command line first IMO.

**Comment by sriv** [comment]
This could be treated similar to Unimplemented Steps. The flow would then look like:

- Gauge sends a StepValidationRequest
- Gauge C# would send back a validation failed response with a new ErrorType = "Duplicate Step Implementations found"

This will ensure that `gauge --validate` would capture duplicate steps. Also, the workflow of execution will be consistent to Unimplemented Steps case i.e the Scenarios with Duplicate/Unimplemented steps will be skipped with warnings.

Thoughts?

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016-06-30
