### ISSUE TITLE
Unable to run gauge specs from different solution

### ISSUE THREAD

**Issue by Buthrakaur** [getgauge/gauge-csharp#60]
I'd like to incorporate gauge `.csproj` into existing solution and reuse some code from existing projects. Unfortunately current gauge-csharp implementation enforces separate `.sln` file exclusively for gauge specs - it tries to compile the solution when invoking gauge executable and fails when no solution file matching the name convention exists.

Is it possible to run specs without compiling the solution? We can compile the solution/project first before invoking `gauge.exe`. The second option would be to leave the compilation, but enable to use some external `.sln` file using a plugin parameter, but I'd prefer gauge wouldn't compile the solution at all - just run the specs if it makes sense according to gauge ecosystem.

**Comment by sriv** [comment]
> Is it possible to run specs without compiling the solution?

Yes, by setting `gauge_custom_build_path` to point to a location that has your compiled binaries (and it's dependencies). This is documented for [Gauge-Java](http://getgauge.io/documentation/user/current/test_code/java/configuration.html#gaugecustom-buildpath), but the same applies for C# as well.

Need to investigate the first point.

**Comment by Buthrakaur** [comment]
@sriv: the `gauge_custom_build_path` works nice, so it's not necessary to implement anything else. I guess you can just close this issue with `gauge_custom_build_path` as the right solution.

**Comment by sriv** [comment]
@Buthrakaur - good to know that the `gauge_custom_build_path` option works for you, but I think this could still be a legitimate issue. 

Ideally, in any solution with existing projects, one should be able to `Add -> New Project -> Gauge Test Project` and start authoring. I suspect that there is some assumption in the way Gauge C# locates the target project that does not work in this scenario, hence the need to investigate this further.

I am keeping this open for now.

**Comment by Buthrakaur** [comment]
@sriv: you're right the `Add -> New Project -> Gauge Test` should be supported. The `gauge_custom_build_path` option is just a workaround.

**Comment by sriv** [comment]
Fix Available in nightly >= 2016-05-10
