### ISSUE TITLE
Creating a solution with own solution directory fails gauge execution

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#61]
**Expected Behavior**
Gauge should be able to execute tests of a solution created using Visual Studio-> New -> Gauge Test Project with 'create directory for solution' .

**Actual Behavior**
Gauge.CSharp.Runner.StartCommand Cannot locate a Project File in Z:\Documents\Visual Studio 2015\Projects\outsideFolder\innerProject\
Failed to start gauge API: Timed out connecting to [::]:64287

**Steps to replicate**
1. Create a Solution using 
```
File->New->Project
In the dialog box - 
Name -> innerProject
Solution name -> outsideFolder
Tick the 'Create a directory for solution'
```
2. A gauge project is created with sample details
3. Goto the cmd line and cd into the outsideFolder/innerProject
4. gauge specs
5. You will see the error. Unable to run the specs from outsideFolder as well.

**Version**
1. MS Visual Studio 2015

```
Gauge version: 0.4.0

Plugins
-------
csharp (0.7.2)
html-report (2.1.0)
java (0.4.0)
ruby (0.2.0)
```

**Comment by sriv** [comment]
Fix Available in nightly >= 2016-05-10
