### ISSUE TITLE
Getting 'Failed to load Gauge api' on refactoring

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#62]
**Expected Behavior**
Refactoring should work seamlessly

**Actual Behavior**
Getting 'Failed to load Gauge api' on refactoring

**Steps to reproduce**
```
mkdir usingTemplate
cd usingTemplate
gauge --init csharp
```

2. execute specs
```
gauge specs
``` 
3. Open the project in Visual Studio
4. Try renaming the step without compiling
5. Get the error
6. This also occurs when the machine is put to sleep for sometime and I start working again

**Version**
VS 2015

```
Gauge version: 0.4.0

Plugins
-------
csharp (0.7.2)
html-report (2.1.0)
java (0.4.0)
ruby (0.2.0)
```

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge-visualstudio#111
