### ISSUE TITLE
Logs getting written in wrong location

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#63]
**Expected behavior**
Logs should get written in the location mentioned in 
```
logs_directory of properties file
```

**Actual behavior**
Logs getting written in wrong location

**Steps to reproduce**
1. Create a gauge csharp project
```
mkdir testing
cd testing
gauge --init csharp
```
2. Edit the environment default.properties file
```
Change logs_directory to somethingElse
```
3. Delete the logs folder if it is existing
4. execute from command line
```
gauge specs
```
5. Both logs and somethingElse directories are created

**Comment by sriv** [comment]
Should work for `logs_directory` being an absolute or relative path.

**Comment by sriv** [comment]
Should be available in nightly >= 2016-05-11.
