### ISSUE TITLE
Unable to refactor a step to have special characters 

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#64]
### Expected behavior
If Implement step is allowed for a given text then refactor to that text should also be allowed

### Actual behavior
Unable to refactor a step to have special characters without building the solution.

### Steps to reproduce
1. Open the project solution. 
```
Do not build it.
```
2. Create a spec
```
kusfdsf sdfsdfsdf
=================

Scenario1
---------

* dfsfsdfddssdf
* Give a discount of 10%

```
2. Implementation
```
Give default implementations by using 'Implement Step'. The code gets generated successfully.
```
3. Now refactor 'dfsfsdfddssdf' to 'something with 10%'
4. It does not change anything

### Gauge version
```
VS2015

Gauge version: 0.4.0

Plugins
-------
csharp (0.7.2)
html-report (2.1.0)
java (0.4.0)
ruby (0.2.0)
```

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge-visualstudio#110
