### ISSUE TITLE
On refactoring, the spec file content changes to the last saved version

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#68]
### Expected behavior
Refactoring should not revert my spec file changes

### Actual behavior
Reverts to the last saved version of the file + new refactoring is applied

### Steps to reproduce
1. Create a spec
```
dfsd
====
kusfdsf sdfsdfsdf
Scenario
--------
* sfdsf "ab" "sdfsdf"
* The word "gauge" has "4" vowels.
* sfdsf "sdf" "wer"
* Almost words have vowels "sdf"
```
2. Give the implementation
```
  [Step("The word <word> has <expectedCount> vowels.")]
        public void VerifyVowelsCountInWord(string word, int expectedCount)
        {
        }

        [Step("Almost words have vowels <wordsTable>")]
        public void VerifyVowelsCountInMultipleWords(Table wordsTable)
        {
        }

[Step("sfdsf <> <sdfsdf>")]
        public void SfdsfSfdwithSfda1(string sdf,string sdfsdf)
        {
            sdf.Should().NotBe("werwerwer");
        }
```
3. Now save the implementation and the spec file
4. Open the spec file
```
ctrl-x on the line
The word "gauge" has "4" vowels.

without saving
Refactor 'sfdsf "sdf" "wer"' to 'sfd "sdf" "wer"'
```
5. The file changes to an inconsistent state
i.e
Reverts to the last saved version of the file + new refactoring is applied

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-05-03

Plugins
-------
csharp (0.7.3.nightly-2016-05-03)
html-report (2.1.1.nightly-2016-05-03)
java (0.4.0)
ruby (0.2.0)
xml-report (0.1.2.nightly-2016-05-03)
```

**Comment by sriv** [comment]
I dont think this is valid here. If you are editing a file in Visual Studio, the file remains in the buffer of Visual Studio (in memory) unless you save it. Gauge-csharp reads and refactors the file only from the disk, which means the file is saved.

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge-visualstudio#109
