### ISSUE TITLE
Can we debug a complete scenario

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge-csharp#69]
Hi,
I am writing scenario where gauge steps are depend on each other so instead of debugging single gauge steps can we initiate debug for scenario and  put debug pointer in step implementation which we want to test. ??

I am using Visual studio 2013

**Comment by sriv** [comment]
I'm afraid this is not possible right now, gauge core does not support any debugging at the moment, and all debugging is done at the language level.

**Comment by itsmemittal** [comment]
i mean, does gauge provide to run or debug scenario from test explorer window. I have visual studio 2015 and trying to run or debug scenario from test explorer like nunit. but not showing any scenario there.

**Comment by sriv** [comment]
Are you saying that you do not see scenarios listed in the test explorer window? It could be a bug, possibly related to getgauge/gauge-visualstudio#93 or getgauge/gauge-visualstudio#105

**Comment by itsmemittal** [comment]
I have installed VS 2013 and installed visual studio plugin and but getting these message in gauge project.

Screen 1
![screen 1](https://cloud.githubusercontent.com/assets/3033471/15190439/83b8cb44-17cd-11e6-98f6-1777b515bb1d.png)

Screen 2
![screen2](https://cloud.githubusercontent.com/assets/3033471/15190475/a9f14ef8-17cd-11e6-9f3d-ff104f22788f.png)

**Comment by itsmemittal** [comment]
gauge is installed on my system and gauge.exe is already in path variable.

**Comment by sriv** [comment]
Is gauge installed as administrator or a different user? Can you try running VS as admin and check?

Also, if you can open the activitylog.xml in a browser and share the error details, that will help troubleshoot.

**Comment by itsmemittal** [comment]
Following is error stack trace 

Failed to start Gauge Daemon: System.Exception: Could not connect ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:1000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
   --- End of inner exception stack trace ---
   at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
   at Gauge.VisualStudio.Core.Helpers.GaugeDaemonHelper.StartGaugeAsDaemon(Project gaugeProject)

**Comment by sriv** [comment]
Thanks for the stack trace - looks like Gauge isn't starting in `daemon` mode correctly, can you also look at the `logs` directory in the project root and check `api.log` and `gauge.log` to see if there is any additional information?

**Comment by itsmemittal** [comment]
Gauge Is Installed on my machine
Gauge_HOME Enviornment is there
Path variable is also there

**Comment by itsmemittal** [comment]
Yes, I see what error was, actually I haven't installed c sharp plugin. Now I am able to see scenarios in  my Test Explorer but when I say debug selected test then it does not hit break point in step implementation.

**Comment by sriv** [comment]
@itsmemittal - there is a new version of Gauge-VisualStudio installed (v 0.2.2). It contains some bug fixes for test runner. Can you please try it? I am closing this issue, please report back if issue still exists.
