### ISSUE TITLE
protected step implementations are not available for execution, however one is taken to it on goto definition

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#72]
**Expected Behavior**
If the protected method is not considered as step implementation it should not be marked as implemented and taken to it when the user says goto definition

**Actual Behavior**
Navigation works as if the method is the implementation

**Steps to reproduce**
1. Create a spec
```
protected method
==================
is not available for execution
-----------
* Should not navigate to step
```
2. Give the implementation
```
        [Step("Should not navigate to step")]
        protected void shouldNotNavigateToStep(Table wordsTable)
        {
}
```
3. execute specs and we get unable to find step
4. Goto the spec, now goto the definition. It takes one to the protected implementation.
5. Plz check private method as well

**Version**
```
VS - 0.2.1
Gauge version: 0.4.1.nightly-2016-05-16

Plugins
-------
csharp (0.7.3.nightly-2016-05-13)
html-report (2.1.1.nightly-2016-05-03)
java (0.4.0)
ruby (0.2.0)
xml-report (0.1.2.nightly-2016-05-03)
```

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge-visualstudio#145
