### ISSUE TITLE
No compatible csharp runner found for gauge nightly

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#73]
### Expected behavior

If the gauge is being installed using the nightly exe, csharp language plugin does not get installed even if selected during installation
### Actual behavior

The langauge selected should get installed.
### Steps to reproduce
1. Download the latest gauge nightly of windows.
2. In the language plugins select c#.
3. gauge is successfully installed with all other plugins except c#.
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-05-18
```

**Comment by sriv** [comment]
@sguptatw - is this still an issue?
