### ISSUE TITLE
Request - Any thoughts for adding DI container support or factory creation method for step classes?

### ISSUE THREAD

**Issue by brunchey** [getgauge/gauge-csharp#75]
Before I go off and build something on my own for this, I am Wondering if there has been any conversation around providing integration with a DI container or even just allowing the ability to provide a custom InstanceManager?

**Comment by sriv** [comment]
@brunchey - thanks for raising this. The answer to your question is: No, there has been no discussion on this.

But this is something Gauge-CSharp could support. Could you elaborate on some use case where this would be helpful? 

If you happen to go down the path of building your own, please consider raising a pull request!

**Comment by BugDiver** [comment]
Available in latest release.
