### ISSUE TITLE
Inner Exceptions of AggregationException are not logged

### ISSUE THREAD

**Issue by ludekcakl** [getgauge/gauge-csharp#81]
### Expected behavior

If test fails with AggregationException than all inner exception stack traces should be part of ExecutionResult.StackTrace
### Actual behavior

Only Message and StackTrace from AggregationException is in the result.
### Steps to reproduce
1. Create test which throws AggregationException containing one or more inner Exceptions
2. Run the test
### Gauge version

0.5.3
### Proposed solution

SandBox.cs:70

```
executionResult.StackTrace =  innerException is AggregationException 
? innerException.ToString() 
: innerException.StackTrace
```

I can make pull request if you are happy with such change

**Comment by sriv** [comment]
Yeah, sounds like a good idea, pull request would be great!

Please note that there is a [CLA](http://getgauge.io/cla/index.html) in place, that you might want to check and sign

**Comment by sriv** [comment]
Fix should be available in nightly >= 19/04/17
