### ISSUE TITLE
Check minimum Lib version supported

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-csharp#84]
As Gauge-CSharp evolves, backward compatibility cannot be always guaranteed. For instance, we have a feature to allow users to wire up an IoC container, this requires shipping a Lib that allows users to do this.

Gauge-CSharp runner expects certain interface to be implemented in order to hookup to the IoC container. 

Hence, error out when user's code uses an old Lib version.

**Comment by sguptatw** [comment]
Can u please specify the steps to upgrade the required libraries.

**Comment by sriv** [comment]
On a Gauge-CSharp project, the Lib version is specified in Nuget's `package.config` file.

If the version of `Gauge.CSharp.Lib` is less than the minimum expected by the corresponding `Gauge.CSharp` runner, then this check kicks in.

For instance, `Gauge.CSharp` v0.9.1 is compatible with `Gauge.CSharp.Lib` >=0.6.0. So, if there is a project with `Gauge.CSharp.Lib` v0.5.3, then the runner would print an incompatibility message. 

Updating the Lib version to 0.6.1 via Nuget Package Manager should then enable the project to be executed.
