### ISSUE TITLE
The generated project from the template is giving lib version error

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#93]
**Expected Behavior**
The project initialization should be seamless taking care of the lib versions.

**Actual Behavior**
Using Gauge Web driver template and initialized the project. Getting the version incompatibility errors on running the specs.

**Comment by sriv** [comment]
Please try updating the project's dependency (for `Gauge.CSharp.Lib`) via Nuget Package Manager. 

The minimum version of `Gauge.CSharp.Lib` for `Gauge.CSharp v0.9.1` is `0.6.0`.

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge-visualstudio#144
