### ISSUE TITLE
Unable to run specs generated using Web driver template

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#94]
Getting the error - Unable to get absolute path to specifications. Failed to find project directory.
After initializing the project using VS IDE Web driver template

**Version**
```
Gauge version: 0.6.2.nightly-2016-08-26

Plugins
-------
csharp (0.9.1.nightly-2016-08-12)
html-report (2.2.0.nightly-2016-08-15)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by sguptatw** [comment]
The report generated in the IDE shows green icons even on failure.

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge-visualstudio#143
