### ISSUE TITLE
Current working  path in csharp(System.Environment.CurrentDirectory) is not working

### ISSUE THREAD

**Issue by AbinashB** [getgauge/gauge-csharp#95]
### Expected behavior

using System.Environment.CurrentDirectory it should give current project directory path
### Actual behavior

using System.Environment.CurrentDirectory , giving where gauge-csharp plugin is working.
example: C:\Users\abiswal\AppData\Roaming\gauge\plugins\csharp\0.9.0
### Steps to reproduce
1. in any step implementation  write  Console.WriteLine(System.Environment.CurrentDirectory);
### Gauge version

Gauge version: 0.6.1
## Plugins

csharp (0.9.0)
html-report (2.1.1)

**Comment by sriv** [comment]
Fix should be available in nightly >= 06/10/2017
