### ISSUE TITLE
On Mono - step failure causes execution to hang

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-csharp#96]
### Expected behavior

On failure, gauge should complete execution and report failures.
### Actual behavior

On spec failure, Gauge execution hangs with exception printed at console.
### Steps to reproduce
1. Initialize `gauge --init csharp`
2. Change `StepImplementation.cs` to throw an exception in a step implementation
3. Run `gauge specs`
### Gauge version

```
Gauge version: 0.6.1

Plugins
-------
csharp (0.9.2)
docker-ruby (0.0.1)
go (0.0.1)
html-report (2.1.1)
java (0.5.1)
js (1.2.1)
m2h (0.0.1)
ruby (0.3.1)
xml-report (0.1.2)
```

**Comment by bkim54** [comment]
I am observing the same problem when running on mac osX. I run` gauge specs` and when a spec fails the mono process's don't kill themselve's

**Comment by bkim54** [comment]
I think this is the process that keeps running `/bin/Gauge.CSharp.Runner.exe --start`

**Comment by sriv** [comment]
@bkim54 - yes, that is the process that is invoked by `gauge`. Ref here: https://github.com/getgauge/gauge-csharp/blob/master/Runner/csharp.json#L13. The `run.sh` in turn [invokes](https://github.com/getgauge/gauge-csharp/blob/master/Runner/run.sh) the exe via Mono.

**Comment by bkim54** [comment]
@sriv I also noticed that even when the gauge tests run successfully this process is still running.

Will this issue be addressed?

**Comment by sriv** [comment]
Funnily enough, I could see this issue on OSx El Capitan, but now I am on macOS sierra, and it seems to exit! Let me troubleshoot it further. I can't seem to see anything wrong with the way the process is invoked.

**Comment by bkim54** [comment]
ah..I am on OSx El capitan, and thanks for looking into it!

**Comment by sriv** [comment]
@bkim54 - do you still see this issue? I have tried to get to a possible cause, but nothing strikes me as wrong. Mono+linux seems to work for me as well.

**Comment by bkim54** [comment]
@sriv yeah it still happens to me, I have to force kill the mono process after

**Comment by sriv** [comment]
@bkim54 - thats a shame. Unfortunately I do not have access to El Capitan anymore, but I will hunt for a machine. In the meantime, I'll see if we can add an option to force kill within Gauge itself. Thanks.

**Comment by sriv** [comment]
@bkim54 - quick check - are you still on El Capitan, do you see this behaviour in any other platform?

**Comment by bkim54** [comment]
@sriv sorry for the late response I thought I had responded. I am still on el capitan. I have not tested on linux yet.

**Comment by sriv** [comment]
Cannot replicate this issue with

```
Gauge version: 0.8.4.nightly-2017-04-05

Plugins
-------
csharp (0.10.0)
```

OS: mac osx 10.11.6 (El Capitan)
Mono: 4.8.0

Closing this, feel free to report back with details if issue persists.
